LU-0000 Do we really need the -source and -default-base rpms?
A test patch to see if Lustre can be built with just kernel-default-devel
on SLES11.

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>
Change-Id: Ieee2b01f9a8c280de5d2cc4c43ff672539eea7ef

diff --git a/contrib/lbuild/lbuild-sles11 b/contrib/lbuild/lbuild-sles11
--- a/contrib/lbuild/lbuild-sles11
+++ b/contrib/lbuild/lbuild-sles11
@@ -68,13 +68,13 @@ unpack_linux_devel_rpm-sles11() {
 
     # this is a hack that should go away when the modified lustre kernel
     # Provides kernel-default-base                        vvvvvvvvv
-    if ! kernelrpm=$(find_rpm "$rpmdir" provides "^kernel-(lustre-)?default-base = $wanted_kernel"); then
-        fatal 1 "Could not find the kernel-default-base in $rpmdir/"
-    fi
-
-    if ! rpm2cpio < "$rpmdir/$kernelrpm" | cpio -id > /dev/null 2>&1; then
-        fatal 1 "Unpack error for $kernelrpm"
-    fi
+    #if ! kernelrpm=$(find_rpm "$rpmdir" provides "^kernel-(lustre-)?default-base = $wanted_kernel"); then
+    #    fatal 1 "Could not find the kernel-default-base in $rpmdir/"
+    #fi
+    #
+    #if ! rpm2cpio < "$rpmdir/$kernelrpm" | cpio -id > /dev/null 2>&1; then
+    #    fatal 1 "Unpack error for $kernelrpm"
+    #fi
 
     if ! kernelrpm=$(find_rpm "$rpmdir" provides "^kernel-(lustre-)?default-devel = $wanted_kernel"); then
         fatal 1 "Could not find the kernel-default-devel in $rpmdir/"
@@ -95,7 +95,7 @@ find_linux_rpm-sles11() {
     local site="https://nu.novell.com/repo/\$RCE/SLES11-SP${PLEV}-Updates/sle-11-$(resolve_arch $TARGET_ARCH)/rpm/$(resolve_arch $TARGET_ARCH)"
     case $prefix in
         -devel)
-            fetch_url "$site/kernel-default-base-$wanted_kernel.$(resolve_arch $TARGET_ARCH).rpm" $pathtorpms
+            #fetch_url "$site/kernel-default-base-$wanted_kernel.$(resolve_arch $TARGET_ARCH).rpm" $pathtorpms
             fetch_url "$site/kernel-default-devel-$wanted_kernel.$(resolve_arch $TARGET_ARCH).rpm" $pathtorpms
             echo "kernel-default-devel-$wanted_kernel.$(resolve_arch $TARGET_ARCH).rpm"
             ;;
