LU-3337 build: add missing build files for sles11sp2 server
Fix lbuild target and config files for sles11sp2 server builds

Signed-off-by: Bob Glossman <bob.glossman@intel.com>
Change-Id: I356d6d7412a5f6f1325a41bb77ba07dbe945b875

diff --git a/contrib/lbuild/lbuild-sles b/contrib/lbuild/lbuild-sles
--- a/contrib/lbuild/lbuild-sles
+++ b/contrib/lbuild/lbuild-sles
@@ -47,12 +47,12 @@ prepare_and_build_srpm() {
 #     commented out!  in fact it should be removed completely before a
 #     landing.
 #if false; then
-    # now build it
-    if ! $RPMBUILD $rpmbuildopt $targets \
-                   --define "_topdir $TOPDIR" \
-                   $TOPDIR/SOURCES/kernel-$RPMSMPTYPE.spec 2>&1; then
-        fatal 1 "Failed to build kernel RPM"
-    fi
+#   # now build it
+#   if ! $RPMBUILD $rpmbuildopt $targets \
+#                  --define "_topdir $TOPDIR" \
+#                  $TOPDIR/SOURCES/kernel-$RPMSMPTYPE.spec 2>&1; then
+#       fatal 1 "Failed to build kernel RPM"
+#   fi
 #fi
 
     # for SLES, we also need to build the kernel-source rpm
