LU-3337 build: add missing build files for sles11sp2 server
Fix lbuild target and config files for sles11sp2 server builds

Signed-off-by: Bob Glossman <bob.glossman@intel.com>
Change-Id: I356d6d7412a5f6f1325a41bb77ba07dbe945b875

diff --git a/contrib/lbuild/lbuild b/contrib/lbuild/lbuild
--- a/contrib/lbuild/lbuild
+++ b/contrib/lbuild/lbuild
@@ -1182,8 +1182,14 @@ find_linux_release() {
     local SRCDIR="$1"
 
     local LINUXRELEASEHEADER=$SRCDIR/include/linux/version.h
-    if [ -s $SRCDIR/include/linux/utsrelease.h ]; then
+    if [ -s $SRCDIR/include/generated/utsrelease.h ]; then
+        LINUXRELEASEHEADER=$SRCDIR/include/generated/utsrelease.h
+    elif [ -s $SRCDIR/include/linux/utsrelease.h ]; then
         LINUXRELEASEHEADER=$SRCDIR/include/linux/utsrelease.h
+    fi
+
+    if [ ! -s $LINUXRELEASEHEADER ]; then
+	fatal 1 "could not find UTS_RELEASE"
     fi
 
     sed -ne 's/#define UTS_RELEASE "\(.*\)"$/\1/p' $LINUXRELEASEHEADER
@@ -1534,7 +1540,7 @@ build_kernel_with_srpm() {
 
     # figure out the EXTRA_VERSION of the kernel we built or are re-using
     local KERNEL_RPM
-    if ! KERNEL_RPM=$(find_rpm "$TOPDIR/RPMS/$TARGET_ARCH/" provides "^kernel ="); then
+    if ! KERNEL_RPM=$(find_rpm "$TOPDIR/RPMS/$TARGET_ARCH/" provides "^kernel(-default)? ="); then
         fatal 1 "Failed to find a kernel RPM in $TOPDIR/RPMS/$TARGET_ARCH/"
     fi
     kernel_extra_version=$(rpm -q --queryformat "%{RELEASE}" -p $TOPDIR/RPMS/$TARGET_ARCH/$KERNEL_RPM)
