LU-0000 build: modify lbuild to build MLNX
Modify lbuild to build MLNX for testing
This patch is based on 2.4.1

Signed-off-by: Minh Diep <minh.diep@intel.com>
Change-Id: Ib771b79a206c329ee2d47127ee6e4077b7442fab

diff --git a/contrib/lbuild/lbuild b/contrib/lbuild/lbuild
--- a/contrib/lbuild/lbuild
+++ b/contrib/lbuild/lbuild
@@ -108,6 +108,9 @@ CONFIG=
 # build the lustre-tests rpm?
 LUSTRE_TESTS=true
 
+# support for building different type of ofed
+OFED_TYPE="MLNX" # set Mellanox just for testing purpose XXX
+
 DATE=$(date)
 
 USE_DATESTAMP=1
@@ -561,33 +564,45 @@ download_ofed() {
         return 0
     fi
 
-    local OFED_BASE_VERSION=$OFED_VERSION
-    if [[ $OFED_VERSION = *.*.*.* ]]; then
-        OFED_BASE_VERSION=${OFED_VERSION%.*}
-    fi
+    case $OFED_TYPE in
+        MLNX)
+            local location="http://www.mellanox.com/downloads/ofed/MLNX_OFED-2.0i/"
+            # we are only interested in the src in the tarball. The arch, distro should not matter
+            local file="MLNX_OFED_LINUX-${OFED_VERSION}-rhel6.4-x86_64.tgz"
+            ;;
+        OFED)
+            local OFED_BASE_VERSION=$OFED_VERSION
+            if [[ $OFED_VERSION = *.*.*.* ]]; then
+                OFED_BASE_VERSION=${OFED_VERSION%.*}
+            fi
 
-    local location="http://www.openfabrics.org/downloads/OFED/ofed-${OFED_BASE_VERSION}/"
+            local location="http://www.openfabrics.org/downloads/OFED/ofed-${OFED_BASE_VERSION}/"
 
-    if [[ $OFED_VERSION = *-[rR][cC][0-9] ]]; then
-        local Mmv
-        Mmv=${OFED_VERSION%%-[rR][cC][0-9]}
-        location="http://www.openfabrics.org/downloads/OFED/ofed-${Mmv}/"
-    fi
+            if [[ $OFED_VERSION = *-[rR][cC][0-9] ]]; then
+                local Mmv
+                Mmv=${OFED_VERSION%%-[rR][cC][0-9]}
+                location="http://www.openfabrics.org/downloads/OFED/ofed-${Mmv}/"
+            fi
 
-    if [[ $OFED_VERSION = daily-* ]]; then
-        local Mmv daily
-        OFED_VERSION=${OFED_VERSION/daily-/}
-        Mmv=${OFED_VERSION%%-*}
-        daily=${OFED_VERSION##$Mmv-}
-        location="http://www.openfabrics.org/downloads/OFED/ofed-${Mmv}-daily/"
-        # find the filename for the version for the date specified
-        OFED_VERSION=$(curl -s "$location" | sed -nre "/${daily}-/s/.*href=\"OFED-(${Mmv//./\\.}-${daily}-[0-9]{4,4}).tgz.*$/\1/p" | tail -1)
-        if [ -z "$OFED_VERSION" ]; then
-            fatal 1 "Could not determine the filename of the OFED snapshot for ${daily}"
-        fi
-    fi
-
-    local file="OFED-${OFED_VERSION}.tgz"
+            if [[ $OFED_VERSION = daily-* ]]; then
+                local Mmv daily
+                OFED_VERSION=${OFED_VERSION/daily-/}
+                Mmv=${OFED_VERSION%%-*}
+                daily=${OFED_VERSION##$Mmv-}
+                location="http://www.openfabrics.org/downloads/OFED/ofed-${Mmv}-daily/"
+                # find the filename for the version for the date specified
+                OFED_VERSION=$(curl -s "$location" | \
+                    sed -nre "/${daily}-/s/.*href=\"OFED-(${Mmv//./\\.}-${daily}-[0-9]{4,4}).tgz.*$/\1/p" | tail -1)
+                if [ -z "$OFED_VERSION" ]; then
+                    fatal 1 "Could not determine the filename of the OFED snapshot for ${daily}"
+                fi
+            fi
+            local file="OFED-${OFED_VERSION}.tgz"
+            ;;
+        *)
+            fatal 1 "Unsupported OFED type ${OFED_TYPE}"
+            ;;
+    esac
     download_file "$location/$file" "$KERNELTREE" "$force"
 
 }
@@ -728,11 +743,30 @@ untar() {
 
 unpack_ofed() {
 
-    if ! untar "$KERNELTREE/OFED-${OFED_VERSION}.tgz"; then
-        return 1
-    fi
-    [ -d OFED ] || ln -sf OFED-[0-9].[0-9]* OFED
-
+    local SRC_DIR
+    # unpack OFED differently depend on how vendor pack it
+    case $OFED_TYPE in
+        MLNX)
+            if ! untar "$KERNELTREE/MLNX_OFED_LINUX-${OFED_VERSION}-rhel6.4-x86_64.tgz" \
+                "MLNX_OFED_LINUX-${OFED_VERSION}-rhel6.4-x86_64/src/MLNX_OFED_SRC-${OFED_VERSION}.tgz"; then
+                return 1
+            fi
+            # we need to untar again to get the src since it's being wrapped inside the tarball
+            if ! untar "MLNX_OFED_LINUX-${OFED_VERSION}-rhel6.4-x86_64/src/MLNX_OFED_SRC-${OFED_VERSION}.tgz"; then
+                return 1
+            fi
+            SRC_DIR="MLNX_OFED_SRC-[0-9].[0-9]*"
+            ;;
+        OFED)
+            if ! untar "$KERNELTREE/OFED-${OFED_VERSION}.tgz"; then
+                return 1
+            fi
+            SRC_DIR="OFED-[0-9].[0-9]*"
+            ;;
+        *)
+            fatal 1 "Unsupported Ofed type $OFED_TYPE"
+    esac
+    [ -d OFED ] || ln -sf ${SRC_DIR} OFED
 }
 
 unpack_lustre() {
@@ -1243,8 +1277,10 @@ build_kernel_ib() {
         K_SRC="KSRC"
     fi
 
-    local OFED_CORE="--with-core-mod --with-ipoib-mod --with-sdp-mod --with-user_mad-mod --with-user_access-mod --with-addr_trans-mod"
-    local OFED_HARDWARE="--with-mthca-mod --with-mlx4-mod --with-mlx4_en-mod --with-cxgb3-mod --with-nes-mod"
+    #local OFED_CORE="--with-core-mod --with-ipoib-mod --with-sdp-mod --with-user_mad-mod --with-user_access-mod --with-addr_trans-mod"
+    local OFED_CORE="--with-core-mod --with-ipoib-mod --with-user_mad-mod --with-user_access-mod --with-addr_trans-mod"
+    #local OFED_HARDWARE="--with-mthca-mod --with-mlx4-mod --with-mlx4_en-mod --with-cxgb3-mod --with-nes-mod"
+    local OFED_HARDWARE="--with-mthca-mod --with-mlx4-mod --with-mlx4_en-mod --with-mlx5-mod"
 
     if compare_version $OFED_VERSION 3.0; then
 	OFED_CORE="$OFED_CORE --with-madeye-mod --with-rds-mod"
@@ -1317,7 +1353,7 @@ EOF
     fi
 
     local linuxrelease=$(find_linux_release "$linux")
-    if compare_version $OFED_VERSION 3.0; then
+    if compare_version $OFED_VERSION 2.0; then
         local OFA_KERNEL_RELEASE=$(echo -n ${linuxrelease} | sed -e 's/-/_/g')
     fi
     if ! $RPMBUILD $BUILD_TYPE --define 'build_kernel_ib 1' --define 'build_kernel_ib_devel 1' \
@@ -1325,7 +1361,6 @@ EOF
                   --define "_topdir ${TOPDIR}" --target ${TARGET_ARCH} \
                   --define "KVERSION ${linuxrelease}" \
                   --define "$K_SRC ${linux}" \
-                  --define "LIB_MOD_DIR /lib/modules/${linuxrelease}/updates" \
                   ${OFA_KERNEL_RELEASE:+--define "_release $OFA_KERNEL_RELEASE"} \
                   --define "configure_options --without-quilt $OFED_CORE $OFED_HARDWARE $OFED_ISCSI" \
                   ${SOURCE} 2>&1; then
@@ -1653,7 +1688,7 @@ build_ofed() {
     # the actual ofed RPMs don't have the -rc$n or -$date string appened that
     # might be present on the file
     local linuxrelease=$(find_linux_release "$linux")
-    ofed_version=$(echo $ofed_version |
+    ofed_version=$(echo ${ofed_version%-*} |
                    sed -re 's/-(20[0-9]{6,6}-[0-9]{4,4}|rc[0-9]*)$//')
     # FIXME
     # OFED version will have 'hyphen' for minor release. (e.g. 3.5-1, instead
@@ -1662,7 +1697,7 @@ build_ofed() {
     # can remove following filter.
     ofed_version=$(echo $ofed_version |
                    sed -re 's/-([0-9]*-[rR][cC][0-9]*)$//')
-    local rpm=$(ls $TOPDIR/RPMS/*/${kib_rpm}-devel-${ofed_version}-${linuxrelease//-/_}.*.rpm)
+    local rpm=$(ls $TOPDIR/RPMS/*/${kib_rpm}-devel-${ofed_version}-${linuxrelease//-/_}*.rpm)
     if ! rpm2cpio < $rpm | cpio -id; then
         fatal 1 "could not unpack the ${kib_rpm}-devel rpm."
     fi
@@ -2071,6 +2106,9 @@ unpack_lustre
 BUILDID=$(sed -ne '/^BUILDID =/s/.*= *//p' lustre/META)
 
 load_target
+
+# XXX hack to force ofed build mlnx
+OFED_VERSION="2.0-2.0.5"
 
 if [ -n "$OFED_VERSION" -a "$OFED_VERSION" != "inkernel" ]; then
     download_ofed
