LU-2445 utils: lfs migrate support
Add a new command migrate to lfs utility.
migrate takes sames args as setstripe.
It:
- create a volatile file based on new stripe information
- copy file data to this volatile file
- swap the 2 layouts

So after migrate the file is restriped (mtime is not
changed)

Signed-off-by: JC Lafoucriere <jacques-charles.lafoucriere@cea.fr>
Change-Id: I96bafb0be9bc273295c4c900c65b4028864fcbaa

diff --git a/lustre/scripts/lfs_migrate b/lustre/scripts/lfs_migrate
--- a/lustre/scripts/lfs_migrate
+++ b/lustre/scripts/lfs_migrate
@@ -147,6 +147,15 @@ lfs_migrate() {
 
 			[ -z "$COUNT" -o -z "$SIZE" ] && UNLINK=""
 		fi
+
+		# first try to migrate inside lustre
+		# if failed go back to old rsync mode
+		$LFS setstripe -c${COUNT} ${LFS_SIZE_OPT}${SIZE} $OLDNAME
+		if [[ $? == 0 ]]; then
+			$ECHO "done"
+			continue
+		fi
+
 		NEWNAME=$(mktemp $UNLINK "$OLDNAME.tmp.XXXXXX")
 		if [ $? -ne 0 -o -z "$NEWNAME" ]; then
 			echo -e "\r$OLDNAME: can't make temp file, skipped" 1>&2
