LU-1935 scripts: don't generate lustre init script
An "overriding commands for target `lustre'" build warning resulted
from the addition of lustre to the genscripts Makefile variable.  In
fact the genscripts processing is superfluous for the lustre script,
so we could just fix the warning by removing it.  However, generating
the script from a .in file seems unnecessarily complicated, so this
change goes a step further by making the script static.  It now
detects at run-time whether to use the ldiskfsprogs or the e2fsprogs
utilities, instead of using autoconf macros to encode it at build
time.

Signed-off-by: Ned Bass <bass6@llnl.gov>
Change-Id: Ie000a87adabbc2a001ed9ff2f5750041a5abea5b

diff --git a/lustre/scripts/lustre b/lustre/scripts/lustre
--- a/lustre/scripts/lustre
+++ b/lustre/scripts/lustre
@@ -41,6 +41,24 @@ ZPOOL_LAYOUT_MAP=${ZPOOL_LAYOUT_MAP:-""}
 MOUNT_DELAY=${MOUNT_DELAY:-2}
 LOAD_ZFS=${LOAD_ZFS:-""}
 
+export TUNE2FS=$TUNE2FS
+if [ -z "$TUNE2FS" ]; then
+	if which tunefs.ldiskfs >/dev/null 2>&1; then
+		export TUNE2FS=tunefs.ldiskfs
+	else
+		export TUNE2FS=tune2fs
+	fi
+fi
+
+export PFSCK=$PFSCK
+if [ -z "$PFSCK" ]; then
+	if which pfsck.ldiskfs >/dev/null 2>&1; then
+		export PFSCK=pfsck.ldiskfs
+	else
+		export PFSCK=fsck
+	fi
+fi
+
 shopt -s nullglob
 
 start_zfs_services ()
@@ -180,15 +198,15 @@ fsck_test ()
 	devices=`echo $devices |xargs -n 1|grep '^/'|xargs`
 
 	if [ -n "${FSCK_ARGS}" -a -n "$devices" ]; then
-		if [ -x /sbin/@PFSCK@ ] ; then
-			echo "@PFSCK@ $devices -- ${FSCK_ARGS}"
-			/sbin/@PFSCK@ $devices -- ${FSCK_ARGS}
+		if [ -x /sbin/$PFSCK ] ; then
+			echo "$PFSCK $devices -- ${FSCK_ARGS}"
+			/sbin/$PFSCK $devices -- ${FSCK_ARGS}
 			if [ $? -ne 0 -a $? -ne 1 ] ; then
-				echo "FAILED: @PFSCK@ -- ${FSCK_ARGS}: $?"
+				echo "FAILED: $PFSCK -- ${FSCK_ARGS}: $?"
 				return 1
 			fi
 		else
-			echo "/sbin/@PFSCK@ not found"
+			echo "/sbin/$PFSCK not found"
 			return 1
 		fi
 	fi
@@ -203,7 +221,7 @@ test_feature_flag()
 	local result=1
 	local feature
 
-	for feature in `/sbin/@TUNE2FS@ -l $dev 2>/dev/null \
+	for feature in `/sbin/$TUNE2FS -l $dev 2>/dev/null \
 				| grep features: | sed -e 's/^.*: //'`; do
 		if [ "$feature" == "$flag" ]; then
 			result=0
@@ -222,13 +240,13 @@ mmp_test ()
 	local result=0
 
 	if [ "$REQUIRE_MMP_FEATURE" == "yes" ]; then
-		if [ -x /sbin/@TUNE2FS@ ]; then
+		if [ -x /sbin/$TUNE2FS ]; then
 			if ! test_feature_flag $dev "mmp"; then
 				echo "mmp feature flag is not set on $dev"
 				result=1
 			fi
 		else
-			echo "/sbin/@TUNE2FS@ not found"
+			echo "/sbin/$TUNE2FS not found"
 			result=1
 		fi
 	fi
