LU-1538 tests: clean up runtests code style
Use $(...) instead of `...` for sub-shells.
Improve some error messages and code style.

Test-Parameters: envdefinitions=SLOW=yes  testlist=runtests
Signed-off-by: Andreas Dilger <andreas.dilger@intel.com>
Change-Id: I4f3eb4a3e288c6fc45ae6ef1fb2008e8e6babe84

diff --git a/lustre/tests/runtests b/lustre/tests/runtests
--- a/lustre/tests/runtests
+++ b/lustre/tests/runtests
@@ -4,8 +4,8 @@
 # Probably a good idea to run this before doing any checkins.
 # In the future this can become more fancy, but it's OK for now.
 
-LUSTRE=${LUSTRE:-`dirname $0`/..}
-SRCDIR="`dirname $0`"
+LUSTRE=${LUSTRE:-$(dirname $0)/..}
+SRCDIR="$(dirname $0)"
 export PATH=/sbin:/usr/sbin:$SRCDIR:$SRCDIR/../utils:$PATH
 
 export NAME=${NAME:-local}
@@ -25,13 +25,12 @@ RUNTESTS_SRC=${RUNTESTS_SRC:-"/etc /bin"}
 
 check_and_setup_lustre
 test_1() {
-OSCTMP=`echo $MOUNT | tr "/" "."`
-USED=`df | awk "/$OSCTMP/ { print \\$3 }" | tail -n 1`
-USED=`expr $USED + 16`	# Some space for the status file
+# Include some extra space for the status file
+USED=$(df -P $MOUNT | awk '{ print $3 }' | tail -n 1)
 
 # let's start slowly here...
-START=`date +%s`
-log "touching $MOUNT at `date`"
+START=$(date +%s)
+log "touching $MOUNT at $(date) (@$START)"
 touch $MOUNT || error "can't touch $MOUNT" 2
 HOSTS=$MOUNT/hosts.$$
 TRUNCSIZE=123
@@ -57,7 +56,7 @@ if [ $COUNT -gt 10 -o $COUNT -eq 0 ]; then
 	$TRUNCATE $HOSTS.2 $TRUNCSIZE
 fi
 
-DST=$MOUNT/runtest.$$
+DST=$MOUNT/runtests.$$
 # let's start slowly here...
 log "creating $DST"
 mkdir $DST || error "can't mkdir $DST" 10
@@ -71,11 +70,11 @@ find $RUNTESTS_SRC -type f -mtime +1 | head -n $COUNT | tr '\n' '\0' > $FILES
 	error "$RUNTESTS_SRC contains only files modifed less than 2 days ago"
 COUNT=$(xargs -0 -n 1 echo < $FILES | wc -l)
 
-log "copying $COUNT files from $RUNTESTS_SRC to $DST$RUNTESTS_SRC at `date`"
+log "copying $COUNT files from $RUNTESTS_SRC to $DST$RUNTESTS_SRC at $(date)"
 tar cf - --null --files-from $FILES | tar xvf - -C $DST > /dev/null ||
 	error "copying $RUNTESTS_SRC" 11
 
-log "comparing $COUNT newly copied files at `date`"
+log "comparing $COUNT newly copied files at $(date)"
 
 cat $FILES | tr "\0" "\n" | ( rc=0; while read f; do
 	[ $V ] && log "verifying $DST/$f"
@@ -83,7 +82,7 @@ cat $FILES | tr "\0" "\n" | ( rc=0; while read f; do
 done
 [ "$rc" = 0 ] || error_exit "old and new files are different: rc=$rc" ) 
 
-log "finished at `date` ($(($(date +%s) - START)))"
+log "finished at $(date) ($(($(date +%s) - START)))"
 
 stopall || exit 19
 setupall || exit 20
@@ -115,16 +114,17 @@ if [ $COUNT -gt 10 -o $COUNT -eq 0 ]; then
 fi
 
 # mkdirmany test (bug 589)
-log "running $MKDIRMANY $MOUNT/base$$ 100"
-$MKDIRMANY $MOUNT/base$$ 100 || error "mkdirmany failed"
-log "removing $MKDIRMANY directories"
-rmdir $MOUNT/base$$* || error "mkdirmany cleanup failed"
+log "running $MKDIRMANY $MOUNT/runtests.$$/d 100"
+$MKDIRMANY $MOUNT/runtests.$$/d 100 || error "mkdirmany failed"
+log "removing 100 directories"
+rmdir $MOUNT/runtests.$$/d || error "mkdirmany cleanup failed"
 
 log "done"
 
-NOWUSED=`df | awk "/$OSCTMP/ { print \\$3 }" | tail -n 1`
-if [ `expr $NOWUSED - $USED` -gt 1024 ]; then
-	echo "Space not all freed: now ${NOWUSED}kB, was ${USED}kB." 1>&2
+wait_delete_completed
+NOWUSED=$(($(df -P $MOUNT | awk '{ print $3 }' | tail -n 1)))
+if [ $(expr $NOWUSED - $USED) -gt 1024 ]; then
+	error "Space not all freed: now ${NOWUSED}kB, was ${USED}kB."
 fi
 }
 run_test 1 "All Runtests"
