bump kernel version for sles11
Signed-off-by: Brian J. Murrell <brian@whamcloud.com>
Change-Id: I84617f429b0cef23a24fe161158580917ffe3041

diff --git a/build/lbuild-sles11 b/build/lbuild-sles11
--- a/build/lbuild-sles11
+++ b/build/lbuild-sles11
@@ -7,6 +7,9 @@ BUILD_GEN+=".0"
 
 source ${0%/*}/lbuild-sles
 
+# do we want to rebuild the OFED devel RPM or use the supplied one?
+REBUILD_OFED_DEVEL_RPM=${REBUILD_OFED_DEVEL_RPM:-false}
+
 edit_specs() {
 
     # edit the SPECs with our changes
@@ -74,5 +77,57 @@ unpack_linux_devel_rpm-sles11() {
     if ! rpm2cpio < "$rpmdir/$kernelrpm" | cpio -id > /dev/null 2>&1; then
         fatal 1 "Unpack error for $kernelrpm"
     fi
+
+    if ! kernelrpm=$(find_rpm "$rpmdir" provides "^kernel-(lustre-)?default-devel = $wanted_kernel"); then
+        fatal 1 "Could not find the kernel-default-devel in $rpmdir/"
+    fi
+
+    if ! rpm2cpio < "$rpmdir/$kernelrpm" | cpio -id > /dev/null 2>&1; then
+        fatal 1 "Unpack error for $kernelrpm"
+    fi
+
+}
+
+find_linux_rpm-sles11() {
+    local prefix="$1"
+    local wanted_kernel="$2"
+    local pathtorpms=${3:-"${KERNELRPMSBASE}/${lnxmaj}/${DISTRO}/${TARGET_ARCH}"}
+
+    # what, oh what, do we do for sles11?
+    # if anyone knows how we get an arbitrary (kernel-source and
+    # kernel-default-base in this case) from the Suse update mechanism,
+    # please feel free to fix this
+
+    fatal 1 "I don't know how to get packages for SLES11"
+
+    return 0
+
+}
+
+build_ofed-sles11() {
+    local outfd=$1
+
+    if [ -z "$outfd" ] || [ $outfd = 1 ]; then
+        fatal 1 "You must supply a file descriptor to ${FUNCNAME[0]} and it cannot be 1"
+    fi
+
+    if $REBUILD_OFED_DEVEL_RPM; then
+        build_sles_ofed_rpm cxgb3-NIC >&${outfd} || return ${PIPESTATUS[0]}
+        build_sles_ofed_rpm >&${outfd} || return ${PIPESTATUS[0]}
+        OFED_DEVEL_LOCATION="${TOPDIR}/RPMS/$(resolve_arch $TARGET_ARCH $PATCHLESS)"
+    fi # $REBUILD_OFED_DEVEL_RPM; then
+
+    # XXX I'm not convinced this belongs in here, but really, this is a
+    # temporary hack until we get a base O/S intalled ofed-devel
+    local arch=$TARGET_ARCH
+    if [ -n "$OFED_VERSION" -a "$OFED_VERSION" = "inkernel" ]; then
+        local ofed_devel="${OFED_DEVEL_LOCATION}/ofed-devel-${OFED_DEVEL_VERSION}.$(resolve_arch $TARGET_ARCH "$PATCHLESS || ! $REBUILD_OFED_DEVEL_RPM").rpm"
+        if ! rpm2cpio < $ofed_devel | cpio -id; then
+            fatal 1 "could not unpack the ofed-devel rpm."
+	fi
+        echo "$(pwd)/usr/src/kernel-modules-ofed/$(resolve_arch $TARGET_ARCH "$PATCHLESS || ! $REBUILD_OFED_DEVEL_RPM")/$RPMSMPTYPE"
+    fi
+
+    return 0
 
 }
