LU-954 build: make lbuild to build lustre-iokit
Add additional codes in lbuild to build lustre-iokit rpm.
It should be noarch because it's independent of any arch.

Signed-off-by: Minh Diep <mdiep@whamcloud.com>
Change-Id: I8b3c0bbaf348c350155d7c50e9ffcb4ec92fe1ff

diff --git a/build/lbuild b/build/lbuild
--- a/build/lbuild
+++ b/build/lbuild
@@ -845,6 +845,40 @@ build_lustre() {
         confoptions="$confoptions --with-ldiskfs=$(ls -d $TOPDIR/BUILD/lustre-ldiskfs-*)"
     }
 
+        pushd lustre-iokit > /dev/null || return 255
+
+        if !  ./configure; then
+            echo "failed to configure in lustre-iokit"
+            popd >/dev/null # pushd lustre-iokit
+            popd >/dev/null # pushd lustre
+            return 255
+        fi
+
+        if ! make dist 2>&1; then
+            popd >/dev/null # pushd lustre-iokit
+            popd >/dev/null # pushd lustre
+            return 255
+        fi
+
+        if ! $RPMBUILD $rpmbuildopt lustre-iokit*.tar.gz \
+            --define "_tmppath /var/tmp" \
+            --define "_topdir $TOPDIR" 2>&1; then
+            popd >/dev/null # pushd lustre-iokit
+            popd >/dev/null # pushd lustre
+            return 255
+        fi
+
+        if $DO_SRC; then
+            if ! $RPMBUILD -ts lustre-iokit*.tar.gz \
+                --define "_tmppath /var/tmp" \
+                --define "_topdir $TOPDIR" 2>&1; then
+                popd >/dev/null # pushd lustre-iokit
+                popd >/dev/null # pushd lustre
+                return 255
+            fi
+        fi
+        popd >/dev/null # pushd lustre-iokit
+
     # convert the $PATCHLESS boolean to an empty/not-empty boolean
     # as silly as this seems, it makes the syntax of the rpmbuild command
     # simpler and not need an eval to deal with the quotes in the quotes
